SET(SOURCES ui_Screen1.c
    ui_Screen2.c
    ui.c
    ui_comp_hook.c
    ui_helpers.c
    ui_img_711420211.c
    ui_img_239613141.c
    ui_img_1691442077.c
    ui_img_389595065.c
    ui_img_izrezak_png.c
    fonts/ui_font_COUNTER.c
    fonts/ui_font_HUGE.c
    fonts/ui_font_large.c
    fonts/ui_font_small.c)

add_library(ui ${SOURCES})
