// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Screen1.h"
#include "ui_Screen2.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_1417965892);   // assets/Steve-Zondicons-Play.48.png
LV_IMG_DECLARE( ui_img_1040054024);   // assets/Pictogrammers-Material-Pause.48.png
LV_IMG_DECLARE( ui_img_1053183376);   // assets/Steve-Zondicons-Forward-Step.48.png
LV_IMG_DECLARE( ui_img_prev_step);   // assets/Steve-Zondicons-Backward-Step.48.png
LV_IMG_DECLARE( ui_img_art6_png);   // assets/art6.png

// FONTS
LV_FONT_DECLARE( ui_font_COUNTER);
LV_FONT_DECLARE( ui_font_HUGE);
LV_FONT_DECLARE( ui_font_large);
LV_FONT_DECLARE( ui_font_small);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
