// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_Arc1;
lv_obj_t *ui_Screen2 = NULL;lv_obj_t *ui_Image1 = NULL;lv_obj_t *ui_Arc1 = NULL;lv_obj_t *ui_timeLBL2 = NULL;lv_obj_t *ui_Label9 = NULL;lv_obj_t *ui_volumeLBL2 = NULL;lv_obj_t *ui_Button6 = NULL;lv_obj_t *ui_Button7 = NULL;lv_obj_t *ui_Roller3 = NULL;lv_obj_t *ui_Button8 = NULL;lv_obj_t *ui_Label10 = NULL;lv_obj_t *ui_Label11 = NULL;
// event funtions
void ui_event_Button6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      nextSelected( e );
}
}

void ui_event_Button7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      prevSelected( e );
}
}

void ui_event_Roller3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      changeSong( e );
}
}

void ui_event_Button8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      playSelected( e );
}
}

void ui_event_Arc1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      changeVolume( e );
}
}

// build funtions

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image1 = lv_img_create(ui_Screen2);
lv_img_set_src(ui_Image1, &ui_img_art6_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image1, 0 );
lv_obj_set_y( ui_Image1, 1 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Arc1 = lv_arc_create(ui_Screen2);
lv_obj_set_width( ui_Arc1, 150);
lv_obj_set_height( ui_Arc1, 150);
lv_obj_set_x( ui_Arc1, -1 );
lv_obj_set_y( ui_Arc1, -69 );
lv_obj_set_align( ui_Arc1, LV_ALIGN_CENTER );
lv_arc_set_range(ui_Arc1, 1,21);
lv_arc_set_value(ui_Arc1, 11);
lv_arc_set_bg_angles(ui_Arc1,0,180);
lv_arc_set_mode(ui_Arc1, LV_ARC_MODE_NORMAL);
lv_arc_set_rotation(ui_Arc1,180);
lv_obj_add_flag(ui_Arc1, LV_OBJ_FLAG_ADV_HITTEST);
lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x102C39), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Arc1, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x4A898B), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Arc1, 14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

ui_timeLBL2 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_timeLBL2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_timeLBL2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_timeLBL2, 271 );
lv_obj_set_y( ui_timeLBL2, 130 );
lv_label_set_text(ui_timeLBL2,"00:12");
lv_obj_set_style_text_color(ui_timeLBL2, lv_color_hex(0xE7E313), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_timeLBL2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_timeLBL2, &ui_font_COUNTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label9 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, -37 );
lv_obj_set_y( ui_Label9, 31 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"VOLUME");
lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x0CD7E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label9, &ui_font_small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_volumeLBL2 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_volumeLBL2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_volumeLBL2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_volumeLBL2, 15 );
lv_obj_set_y( ui_volumeLBL2, 31 );
lv_obj_set_align( ui_volumeLBL2, LV_ALIGN_CENTER );
lv_label_set_text(ui_volumeLBL2,"10");
lv_obj_set_style_text_color(ui_volumeLBL2, lv_color_hex(0x4A9194), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_volumeLBL2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_volumeLBL2, &ui_font_small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button6 = lv_btn_create(ui_Screen2);
lv_obj_set_width( ui_Button6, 52);
lv_obj_set_height( ui_Button6, 46);
lv_obj_set_x( ui_Button6, 112 );
lv_obj_set_y( ui_Button6, 17 );
lv_obj_set_align( ui_Button6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button6, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0x4A9193), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Button6, &ui_img_1053183376, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_recolor(ui_Button6, lv_color_hex(0x082839), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(ui_Button6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button7 = lv_btn_create(ui_Screen2);
lv_obj_set_width( ui_Button7, 52);
lv_obj_set_height( ui_Button7, 46);
lv_obj_set_x( ui_Button7, -112 );
lv_obj_set_y( ui_Button7, 17 );
lv_obj_set_align( ui_Button7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button7, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0x4A9193), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Button7, &ui_img_prev_step, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_recolor(ui_Button7, lv_color_hex(0x082839), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(ui_Button7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Roller3 = lv_roller_create(ui_Screen2);
lv_roller_set_selected( ui_Roller3, 5, LV_ANIM_OFF);
lv_obj_set_width( ui_Roller3, 284);
lv_obj_set_height( ui_Roller3, 91);
lv_obj_set_x( ui_Roller3, 0 );
lv_obj_set_y( ui_Roller3, 117 );
lv_obj_set_align( ui_Roller3, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_Roller3, lv_color_hex(0x98C6DF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Roller3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Roller3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Roller3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Roller3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Roller3, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Roller3, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller3, lv_color_hex(0x051B2C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Roller3, lv_color_hex(0x24CAF6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Roller3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Roller3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Roller3, lv_color_hex(0x184862), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller3, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Button8 = lv_btn_create(ui_Screen2);
lv_obj_set_width( ui_Button8, 52);
lv_obj_set_height( ui_Button8, 46);
lv_obj_set_x( ui_Button8, 3 );
lv_obj_set_y( ui_Button8, -70 );
lv_obj_set_align( ui_Button8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button8, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0x4A9193), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Button8, &ui_img_1417965892, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_recolor(ui_Button8, lv_color_hex(0x082839), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(ui_Button8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label10 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, -143 );
lv_obj_set_y( ui_Label10, -39 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"BAT:");
lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x081820), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label11 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label11, 56 );
lv_obj_set_y( ui_Label11, 134 );
lv_label_set_text(ui_Label11,"100%");
lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x7AE0FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Roller3, ui_event_Roller3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Arc1, ui_event_Arc1, LV_EVENT_ALL, NULL);
uic_Arc1 = ui_Arc1;

}

void ui_Screen2_screen_destroy(void)
{
   if (ui_Screen2) lv_obj_del(ui_Screen2);

// NULL screen variables
ui_Screen2= NULL;
ui_Image1= NULL;
uic_Arc1= NULL;
ui_Arc1= NULL;
ui_timeLBL2= NULL;
ui_Label9= NULL;
ui_volumeLBL2= NULL;
ui_Button6= NULL;
ui_Button7= NULL;
ui_Roller3= NULL;
ui_Button8= NULL;
ui_Label10= NULL;
ui_Label11= NULL;

}
