// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Label1;
extern void ui_event_Roller1( lv_event_t * e);
extern lv_obj_t *ui_Roller1;
extern void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern void ui_event_Button3( lv_event_t * e);
extern lv_obj_t *ui_Button3;
extern void ui_event_Slider1( lv_event_t * e);
extern lv_obj_t *ui_Slider1;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_volumeLBL;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_timeLBL;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_Panel8;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Panel9;
extern lv_obj_t *ui_Panel10;
extern lv_obj_t *ui_coverart;
extern void ui_event_Button4( lv_event_t * e);
extern lv_obj_t *ui_Button4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

