// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Arc1;
extern lv_obj_t *ui_timeLBL2;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_volumeLBL2;
extern void ui_event_Button6( lv_event_t * e);
extern lv_obj_t *ui_Button6;
extern void ui_event_Button7( lv_event_t * e);
extern lv_obj_t *ui_Button7;
extern void ui_event_Roller3( lv_event_t * e);
extern lv_obj_t *ui_Roller3;
extern void ui_event_Button8( lv_event_t * e);
extern lv_obj_t *ui_Button8;
extern void ui_event_Arc1( lv_event_t * e);
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Label11;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Arc1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

