; ESP32-S3-Touch-LCD-1.85 — Waveshare Arduino mp3Player sketch
; https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-1.85

[platformio]
src_dir = .
lib_dir = lib
include_dir = include

[env:waveshare_s3_1_85]
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.311
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
board_upload.maximum_size = 16777216
upload_port = /dev/cu.usbmodem1401
monitor_port = /dev/cu.usbmodem1401
build_flags =
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DLV_CONF_INCLUDE_SIMPLE
	-DLV_LVGL_H_INCLUDE_SIMPLE
	-I${PROJECT_DIR}/include
	-I${PROJECT_DIR}
build_src_filter =
	+<*>
	-<Wireless.cpp>
	-<lib/>
	-<include/>
	-<assets/>
	-<autosave/>
	-<backup/>
	-<cache/>
	-<.pio/>
lib_ldf_mode = chain
lib_compat_mode = soft
lib_deps =
	Wire
	FS
	SD_MMC
	SPI
	SPIFFS
	FFat
	SD
	WiFi
	Network
	NetworkClientSecure
	ESP32Time
